# Generated by Django 5.1.3 on 2024-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_invoiceproduct_cost_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
