# Generated by Django 5.1.3 on 2024-11-08 19:07
import logging

from django.contrib.auth.models import Group
from django.db import migrations


def populate_initial_roles(apps, schema_editor):
    """Add initial list of grade equivalents"""

    roles = ['Admin', 'Warehouse Manager', 'Salesperson', 'Cashier']

    # Group = apps.get_model("django.contrib.auth", "Group")
    for role in roles:
        try:
            Group.objects.get_or_create(name=role)
        except Exception as exc:
            logging.warning(exc)


def reverse_operation(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_product_stock_value_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_initial_roles, reverse_operation),
    ]
