# Generated by Django 5.1.3 on 2024-11-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
    ]
